### PR TITLE
my-render-branch

### PR DESCRIPTION
**Pull request by JoelleKado**

### CODE REVIEW

**Review by jposeyjr — APPROVED** [review]
Good job  🌟 🌟 🌟 🌟 🌟

**Review by JoelleKado — COMMENTED** [review]
resolved conflicts

**Review by jposeyjr — DISMISSED** [review]
😁😁😁

**Review by jposeyjr — APPROVED** [review]
Way to go.

**Review by jposeyjr — CHANGES_REQUESTED** [review]
Remove comments of un-needed code.

**Review by jposeyjr — APPROVED** [review]

**Review by BPJ94487 — APPROVED** [review]

**Pull request merged**
